### ISSUE TITLE
Suggestion for support of fluent configuration

### ISSUE THREAD

**Issue by davidkeaveny** [AltairCA/EntityFrameworkCore.PostgreSQL.ColumnEncryption#7]
Would it be possible to add support for encrypting columns via extension methods on the `PropertyBuilder<T>` so that I can add encryption support to my model via the `IEntityTypeConfiguration<T>` interface rather than having to decorate my model with additional attributes?

e.g.

```
public class EmployeeConfiguration : IEntityTypeConfiguration
{
  public void Configure(EntityTypeBuilder<Employee> builder)
  {
    builder
      .Property(t => t.MySecretValue)
      .HasColumnName("my_secret_value")
      .IsEncrypted();  
  }
}
```

**Comment by AltairCA** [comment]
done :)

**Comment by AltairCA** [comment]
use the following extension

```csharp
public class TestingConfiguration:IEntityTypeConfiguration<Testings>
{
    public void Configure(EntityTypeBuilder<Testings> builder)
    {
        builder.Property(x => x.encrypted)
            .UseEncryption("NBJ42RKQ2vQoYFZOj1C83921vHExVhVp1PlOAK6gjbMZI", EncKeyLength.L128);
    }
}

```

**Comment by davidkeaveny** [comment]
Wow, thanks for the fast turn-around on this suggestion! One small question - in your example above, you have hard-coded the encryption key; do you have any suggestions for how to make that configurable?

**Comment by AltairCA** [comment]
you can inject that using Configurations or using any other provider to the DbContext and then pass that to the configuration
